name: Tests

on: [push, pull_request]

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 21]
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Test
        run: bun test